name: PR
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
jobs:
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    env:
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      SUBQL_ACCESS_TOKEN_TEST: ${{ secrets.SUBQL_ACCESS_TOKEN_TEST }}
      SUBQL_ORG_TEST: ${{ secrets.SUBQL_ORG_TEST }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: yarn
    - name: build
      run: yarn build
    - name: code-style check
      run: yarn pretty-quick --check --pattern 'packages/*/src/**/*' --branch origin/main
    - name: lint
      run: yarn lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          package-manager: yarn
